# Generated by Django 3.2 on 2025-04-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_created_at',)},
        ),
    ]
