# Generated by Django 4.2.20 on 2025-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_lecturer_alter_course_id_alter_enroll_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_topic',
            field=models.ManyToManyField(null=True, to='courses.topic', verbose_name='Course Topic'),
        ),
    ]
